export type ConditionName =
  | "always"
  | "doesNotHaveTallNeighbors"
  | "hasOneActiveWorker"
  | "hasOneOrMoreColonists"
  | "hasThreeActiveWorkers"
  | "hasThreeOrMoreColonists"
  | "hasTwoActiveWorkers"
  | "hasTwoOrMoreColonists"
  | "isDay"
  | "isInBuildRange"
  | "isNotBlocked"
  | "isNotOnEdgeOfMap"
  | "isNotOnOtherBuilding"
  | "isOnFertile"
  | "isOnOre"
  | "isPowered"
  | "willNotHaveAdjacentShields";
