export type EffectId =
  | "CLEAR_UI_OVERHEAT"
  | "DESTROY"
  | "ON_COLONIST_DESTROYED"
  | "ON_ROAD_BUILD"
  | "SPAWN_BUILDING_WALL_CRACKED"
  | "SPAWN_BUILDING_WALL_CRUMBLING"
  | "SPAWN_ENEMY_DRONE"
  | "SPAWN_PLAYER_CORPSE";
